services:
    homedash-rs:
        container_name: homedash-rs
        network_mode: host
        environment:
            - PUID=1000 # Replace with your user ID
            - PGID=1000 # Replace with your group ID
            - TZ=Europe/Berlin # Replace with your timezone
        volumes:
            - ./data:/app/data # Replace with your data directory
        restart: unless-stopped
        image: ghcr.io/nzxl101/homedash-rs:latest@sha256:f6fc983fdc131fb1684c5d5cda63988f8b4e49a279964caefd2e4b96ea039d33
